### ISSUE TITLE
Not generating anything other than jsonSchema

### ISSUE THREAD

**Issue by antoniormrzz** [psteinroe/supabase-to-zod#18]
I had this problem, so I asked for the supabase ts file (input) from a coworker, and only one line was different.
`export interface Database {` was `export type Database = {` for me, and after changing it to interface, the output file was generated properly.

**Comment by AndyLeezard** [comment]
I confirm this too.
There should be an update.

**Comment by psteinroe** [comment]
sorry, was on vacation. thanks @AndyLeezard for fixing this!

**Comment by mattcoker** [comment]
@psteinroe  Any chance we could get an updated release with this fix? Thanks!

**Comment by psteinroe** [comment]
sorry, had to update some versions in the release action for it to work again. new release is now out! thanks for the contribution everyone.
